rdp-server: add timer management within the eventloop
ogon-project/ogon pull request #40
Opened 2021-01-13 14:13 UTC by hardening

Implement timers natively in the ogon eventloop and change existing code to using them.

2021-01-19 13:45 UTC, hardening commented
Super interesting PR !

2021-01-26 16:20 UTC, hardening commented
@nfedera @bmiklautz anyone to have a look at that interesting PR that simplifies the code with timers a lot (and have unitary tests !) ?

2021-04-14 06:49 UTC, hardening commented
This is really good stuff, don't hesitate to review and merge !

2021-04-15 16:59 UTC, bmiklautz commented
@hardening sorry for the long delay but finally on it

As a start the new Test fails on my machine with a counter of `0`.

2021-04-15 17:01 UTC, bmiklautz commented
@hardening what FreeRDP version is required for it?

2021-04-15 17:12 UTC, bmiklautz requested changes

2021-04-15 17:12 UTC, bmiklautz commented on rdp-server/test/TestOgonTimer.c
> +	DWORD endDate;
this should be a ULONGLONG (or UINT64)

2021-04-15 17:13 UTC, bmiklautz commented
@hardening thank you for the nice addition! - Just tested it with base connections and shadowing. With the one remark is fixed it's good to go for me!

2021-04-15 21:10 UTC, merged